module.exports = {
  USER: {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
  },
  EMPLOYEE: {
    GET_EMPLOYEE: 'GET_EMPLOYEE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  },
  TRANSACTION: {
    GET_TRANSACTION: 'GET_TRANSACTION',
  },
};
